apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-newlife
spec:
  selector:
    matchLabels:
      app: server-newlife
  strategy:
    type: Recreate
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: server-newlife
        stage: production
        kuvel.azisaba.net/enable-server-discovery: "true"
        kuvel.azisaba.net/preferred-server-name: newlife
        kuvel.azisaba.net/disable-load-balancer: "true"
        kuvel.azisaba.net/disable-name-suffix: "true"
    spec:
      nodeName: saba15
      containers:
      - name: server-newlife
        image: itzg/minecraft-server:java25
        workingDir: /data
        imagePullPolicy: Always
        resources:
          requests:
            memory: "16Gi"
          limits:
            memory: "24Gi"
        ports:
          - containerPort: 25565
        env:
          - name: TZ
            value: "Asia/Tokyo"
          - name: EULA
            value: "true"
          - name: TYPE
            value: PAPER
          - name: USE_AIKAR_FLAGS
            value: "true"
          - name: SPAWN_PROTECTION
            value: "0"
          - name: ONLINE_MODE
            value: "false"
          - name: ENABLE_COMMAND_BLOCK
            value: "true"
          - name: ALLOW_NETHER
            value: "false"
          - name: ALLOW_FLIGHT
            value: "true"
          - name: SNOOPER_ENABLED
            value: "false"
          - name: ANNOUNCE_PLAYER_ACHIEVEMENTS
            value: "false"
          - name: MAX_PLAYERS
            value: "1000"
          - name: UID
            value: "0"
          - name: GID
            value: "1011"
          - name: VERSION
            value: 1.21.11
          - name: MEMORY
            value: 16G
          - name: ENABLE_WHITELIST
            value: "false"
          - name: JVM_OPTS
            value: "-XX:MaxJavaStackTraceDepth=999999 -DPaper.IgnoreJavaVersion=true -XX:+UseCompactObjectHeaders -XX:+UseStringDeduplication"
          - name: VIEW_DISTANCE
            value: "8"
          - name: ENV_VARIABLE_PREFIX
            value: "CFG_"
          - name: CFG_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: CFG_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: CFG_SERVER_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['kuvel.azisaba.net/preferred-server-name']
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: SERVER_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['kuvel.azisaba.net/preferred-server-name']
        startupProbe:
          tcpSocket:
            port: 25565
          failureThreshold: 60
          periodSeconds: 10
        volumeMounts:
        - name: server-data
          mountPath: /data
        # - name: hdd1-storage
        #   mountPath: /data/plugins/TAB
        #   subPath: plugins/TAB
        - name: tab-config
          mountPath: /plugins/TAB/config.yml
          subPath: config.yml
        # 要変更
        # - name: raid-storage
        #   mountPath: /mnt/raid/srv/life
      volumes:
      # - name: server-data
      #   hostPath:
      #     path: /mnt/hdd1/srv/newlife
      #     type: Directory
      - name: tab-config
        configMap:
          name: common-life-server-tab-config-with-pvelevel
      # - name: hdd1-storage
      #   hostPath:
      #     path: /mnt/hdd1/srv/newlife
      #     type: Directory
      priorityClassName: minecraft-other-server
      terminationGracePeriodSeconds: 60
---
apiVersion: v1
kind: Service
metadata:
  name: server-newlife-svc
spec:
  type: ClusterIP
  selector:
    app: server-newlife
    stage: production
  ports:
    - port: 25565
      targetPort: 25565
---
apiVersion: v1
kind: Service
metadata:
  name: server-newlife-lifecore-svc
spec:
  type: ClusterIP
  selector:
    app: server-newlife
    stage: production
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: server-newlife-bluemap-svc
spec:
  type: ClusterIP
  selector:
    app: server-newlife
    stage: production
  ports:
    - port: 8100
      targetPort: 8100
---
apiVersion: v1
kind: Service
metadata:
  name: server-newlife-prometheus-exporter-svc
spec:
  type: ClusterIP
  selector:
    app: server-newlife
    stage: production
  ports:
    - port: 9225
      targetPort: 9225
